Traceback (most recent call last):
  File "/usr/local/share/COMMON/CLINICAL_SHARE/GatorSeq/DevEnv/gatorseq_linux_code/QCI_download.py", line 15, in <module>
    print(datetime.datetime.now() + "\n")
TypeError: unsupported operand type(s) for +: 'datetime.datetime' and 'str'
2019-06-14 15:23:02.767969

2019-06-14 15:24:02.538549

2019-06-14 15:25:02.148147

2019-06-14 15:26:02.132462

2019-06-14 15:27:01.766620

2019-06-14 15:28:02.509737

2019-06-14 15:29:02.392419

2019-06-14 15:30:02.029009

2019-06-14 15:31:02.676519

2019-06-14 15:32:02.663189

2019-06-14 15:33:01.773064

2019-06-14 15:34:02.244353

2019-06-14 15:35:02.587331

2019-06-14 15:36:02.148298

2019-06-14 15:37:02.295651

2019-06-14 15:38:02.037092

2019-06-14 15:39:01.934045

2019-06-14 15:40:02.679676

2019-06-14 15:41:02.242985

2019-06-14 15:42:02.148980

2019-06-14 15:43:02.079433

2019-06-14 15:44:01.891827

2019-06-14 15:45:02.154963

2019-06-14 15:46:02.572366

2019-06-14 15:47:02.002017

2019-06-14 15:48:01.783894

2019-06-14 15:49:02.328341

2019-06-14 15:50:02.046853

2019-06-14 15:51:01.695360

2019-06-14 15:52:02.446103

2019-06-14 15:53:02.285423

2019-06-14 15:54:02.229195

2019-06-14 15:55:02.173653

2019-06-14 15:56:02.180729

